### PR TITLE
Handle null values in fieldtypes

### PR DESCRIPTION
**Pull request by ryanmitchell**
Fixes: #286 

When attributes are added after a product / variant exists, they will be null and throw an error if being saved through code. So we need to handle this in the getValue() check.

### CODE REVIEW

**Comment by glennjacobs** [comment]
@ryanmitchell any chance you could fix up the tests on this one, so we can include in the next release?

**Comment by ryanmitchell** [comment]
Probably not today. I need to think about how to get around the test failures (or if indeed I should). I’ll move to draft for now.

**Comment by glennjacobs** [comment]
@ryanmitchell will you be able to finish this up? Be good to get this one out the way.

**Comment by ryanmitchell** [comment]
I need to get some time to do some digging to see if it’s still an issue and the best approach to fix it. 

On holidays at the moment so won’t be able to look at it for a couple of weeks.

**Comment by ryanmitchell** [comment]
Ive updated it to only care about the toString() return value, which handles the livewire issues I was seeing. I may need another PR to address the original issue, but for now this is enough to get me moving again.

**Review by alecritson — APPROVED** [review]

**Pull request merged**
