### PR TITLE
Package assets

### PR DESCRIPTION
**Pull request by theimerj**
### Basic information

This PR makes it possible to register package assets. Please take it as an exploration process for now. It allows registering of scripts for now, styles can be easily added. It utilises GetCandyHub class as a container for scripts.

Main benefit is that the package assets do not have to be published with `vendor:publish`, because they will be resolved by a controller which returns it with correct headers defined in `Script.php`.

### Example of registering scripts in a package service provider

```php
/**
 * Bootstrap the application services.
 */
public function boot()
{
    // ...

    FieldTypeManifest::add(
        Multiselect::class
    );

    GetCandyHub::script('getcandy-multiselect', __DIR__.'/../dist/getcandy-multiselect.js');

    // ...
}

```

### Other possible approach

Other approach would be to create something like AssetManifest class with scripts and styles arrays. It would be used pretty much the same way, just separated from the main GetCandyHub class.

### Possible enhancements

- register styles (or any other asset types actually)
- possibility to register remote styles
- check if assets are published and use those if they are

### What needs to be done

- [x] add the option to register package styles as well
- [x] update documentation
- [ ] tests?

### What's next

Would you consider this solution as a way to go?
Does it break some of your internal ideas about this package?
Shall I continue developing this feature further?

### Credits

This solution is heavily inspired by how Laravel Nova registeres assets.

### CODE REVIEW

**Comment by theimerj** [comment]
@ryanmitchell

**Comment by glennjacobs** [comment]
Many thanks, I will review the approach with @alecritson and come back to you.

**Comment by glennjacobs** [comment]
@alecritson we could do with reviewing this

**Comment by glennjacobs** [comment]
Hey @theimerj 

Thanks ever so much for putting this together. I've reviewed with @alecritson and we're happy with the approach. If you could carry on so that it supports stylesheets etc and then submit for review, that would be awesome.

This also will help us get away from CDN links etc.

**Comment by theimerj** [comment]
Hey @glennjacobs, thank you for the review. I will carry on then and let you know when finished.

**Comment by theimerj** [comment]
Hey @glennjacobs and @alecritson, I progressed with the PR. I finished the possibility to register styles and added also the possibility to use external styles and scripts.

Now you can do it as follows:

```php
// Register compiled script
GetCandyHub::script('getcandy-package', __DIR__.'/../dist/getcandy-package.js');

// Register remote script
GetCandyHub::remoteScript('https://example.com/script.js');

// Register compiled styles
GetCandyHub::style('getcandy-package', __DIR__.'/../dist/getcandy-package.css');

// Register remote styles
GetCandyHub::remoteStyle('https://example.com/style.css');
```
This can be also seen in the documentation. Please tell me if it is ok, or shall I rewrite it, add more examples and so on.

I think that now it will be possible to register all GetCandyHub styles and scripts with this methods.

The only thing that is missing are the tests. I will need a bit more time to finish them. But the functionality is easily user testable for now. I can add them later. Up to you.

**Comment by glennjacobs** [comment]
@theimerj are you able to fix the conflicts? Thx

**Comment by theimerj** [comment]
> @theimerj are you able to fix the conflicts? Thx

Yeah sure, done.

**Review by glennjacobs — CHANGES_REQUESTED** [review]
All looks good, but the tests are empty? They will need to be completed before we can merge this PR.

**Comment by theimerj** [comment]
Ok, I will add the tests shortly.

**Comment by theimerj** [comment]
Hey @glennjacobs, I added some tests. Just tell me if you want to test for anything else.

**Comment by theimerj** [comment]
Hello @glennjacobs, I fixed the tests, the whole suit should now run ok. 

I came across a problem when I could not run the tests at all, which seems to be an error with doctrine dbal package, described here: [https://github.com/doctrine/dbal/issues/5584](https://github.com/doctrine/dbal/issues/5584). I had to manually downgrade to `v3.3` in order to run the suit.

**Review by glennjacobs — APPROVED** [review]

**Pull request merged**
