### PR TITLE
Feat - Add multiple lines to the cart

### PR DESCRIPTION
**Pull request by markmead**
This PR adds a function called `addLines` that allows for bulk adding to the cart.

It doesn't add anything too exciting but it's functionality I had to create that I thought could be good in the core.

### CODE REVIEW

**Comment by markmead** [comment]
Sure! Here's what I was doing:

```php
foreach ($this->purchasableCart->lines as $line) {
    CartSession::add(
        $line->purchasable,
        $line->quantity
    );
}
```

But with the update I can do:

```php
CartSession::addLines($this->purchasableCart->lines);
```

It's not much so I understand if it's a no to moving this into the core.

**Comment by alecritson** [comment]
Yeah, I can see a use for it, like if you had a page where you could add multiple quantities of each variant in one go you don't have to loop through doing multiple queries.

**Comment by glennjacobs** [comment]
Things that concern me are...

1) Passing a Collection through gives no structure to what is expected.
2) Only allows Collections, what if we want to pass something else that can be iterated, such as an array?

**Comment by glennjacobs** [comment]
@markmead can you add docs for this?

**Review by glennjacobs — APPROVED** [review]

**Pull request merged**
