### PR TITLE
Add attributes to customers

### PR DESCRIPTION
**Pull request by ryanmitchell**
This PR adds attributes to the Customers model, attribute editing to the customer edit hub screen, and includes a unit test for the livewire interaction.

If you want any changes just let me know.

### CODE REVIEW

**Comment by glennjacobs** [comment]
I presume we'd need to add attribute editing for Customers to the Settings area?

**Comment by ryanmitchell** [comment]
Adding it to the attributesmanifest was enough for that to already work

**Comment by glennjacobs** [comment]
> Adding it to the attributesmanifest was enough for that to already work

Magic.

**Comment by alecritson** [comment]
@ryanmitchell Looks like one of the tests is failing. I think it's just missing an import

**Comment by ryanmitchell** [comment]
Yep thats fixed now - I need to get a proper GetCandy dev environment set up as I'm just copying over files from our project at the moment... !

**Comment by glennjacobs** [comment]
@alecritson do you want to manually check this before we merge?

**Pull request merged**
