### PR TITLE
fix floating point precision error in unit price calc

### PR DESCRIPTION
**Pull request by daikazu**
fix for issue #325 

My apologies but I couldn't create a test for this at the moment.

### CODE REVIEW

**Comment by alecritson** [comment]
Thanks for submitting this @daikazu , although there is a link to the issue, can you explain what the change is doing in a bit of detail? Would this affect other currencies etc?

**Comment by daikazu** [comment]
So I updated the pull request to a simpler solution which does not require someone to have the PHP BC Math Functions extension. Essentially I moved the rounding of the unit_price last before it is cast to an int. You should generally always round at the very end when doing any kind of monitory calculations like this. When selling in large volumes loosing a penny on the unit price really adds up over time.

I extracted and created a little [example ](https://3v4l.org/P06DF#v8.1.7) demonstrating the problem and showing the solution results. I hope that helps. I've tested it with other decimal places and it seems to work correctly.


Not necessarily within in the same scope of this fix but I also see a potential problem where you are getting a unit price based off of `$price->decimal / $purchasable->getUnitQuantity()` within the same piece of code.  If that get's rounded off and then multiplied later by the quantity, the results are going to be off also.

**Comment by daikazu** [comment]
Hey @alecritson,  I added a test that addresses the initial rounding issue. I used a known failing value because creating a big loop to test through would chug and use a lot of memory because it requires adding a lot of lines to the cart. I can add the looping checks if needed though.

This still doesn't address the problem if the ProductVariant unit_quantity is more than 1. When I have a few moments I'll dig a little deeper into the code to see what all needs to be done to address this, create an issue if was does not already exist, and work up a fix for it. I'm sure just moving all the decimal rounding for currency to just before the output would solve it.

**Comment by alecritson** [comment]
Thanks @daikazu that makes sense. I'll have a chat with @glennjacobs and see if we can get this in the next release. Thanks again for your work on this!

**Review by glennjacobs — APPROVED** [review]

**Pull request merged**
