### PR TITLE
Bug: dashboard placed_at throws error when null

### PR DESCRIPTION
**Pull request by ryanmitchell**
This PR wraps it in `optional()`

### CODE REVIEW

**Comment by alecritson** [comment]
We haven't used optional in the code before this. What's your thoughts on using `$order->placed_at?->format('jS F Y h:ma')` instead? @glennjacobs @ryanmitchell

**Comment by glennjacobs** [comment]
> We haven't used optional in the code before this. What's your thoughts on using `$order->placed_at?->format('jS F Y h:ma')` instead? @glennjacobs @ryanmitchell

Have we used `?` in other views then?

**Comment by alecritson** [comment]
Not so much in other views but it has been used in code in GetCandy.

**Comment by alecritson** [comment]
After chatting we're going to go with `optional`

**Pull request merged**
