### PR TITLE
Bug fix: don't assume `id` is the user key

### PR DESCRIPTION
**Pull request by ryanmitchell**
Use getKey() instead

### CODE REVIEW

**Comment by alecritson** [comment]
Thanks @ryanmitchell , does this open more questions... Since the `user_id` column is constrained, if it's not the `id` column on the `users` table then `whereUserId()` would be incorrect to no? 🤔

**Comment by ryanmitchell** [comment]
So the use case is logging in via Statamic using the user:login form - it provides a `Statamic\Auth\Eloquent\User` instance which is an abstraction - its not a `App\Models\User` instance.

getKey() works in this scenario and under conditions too.

**Comment by alecritson** [comment]
Thanks, I think it'd be good to change to `getKey` although there are some other places that would need to be changed I think where we use `$user->id` so I think these should be updated to be consistent. I'm happy to do that and then merge this when done or it can be part of this PR?

When I had a look there isn't many places that I could see, let me know what you'd prefer.

image

**Comment by ryanmitchell** [comment]
No problem - I've updated them all

**Review by alecritson — APPROVED** [review]
Thank you for sorting this! I'll get this merged then if you want to use it before the release you can target the main branch.

**Pull request merged**
