### PR TITLE
Fix directory path (remove slashes)

### PR DESCRIPTION
**Pull request by iboldurev**

### CODE REVIEW

**Comment by iboldurev** [comment]
Hi, please merge this fix

**Comment by glennjacobs** [comment]
What does it fix? And please supply a test.

**Comment by iboldurev** [comment]
This fixes the path for getting information about the package (addons)

You can create new addon and run getcandy:addons:discover

**Comment by bengs** [comment]
I had this problem too (on Mac OS) with a default demo install you'll get FileNotFoundException exception for the stripe add-on when visiting the `/hub/settings/addons` page:
File does not exist at path `/Users/username/Sites/getcandydemo/vendor/getcandy/stripe/srccomposer.json`. 

You can replicate the error on an existing install by deleting the addons manifest cache if it exists at:
`/bootstrap/cache/getcandy_addons.php` then visiting the /hub/settings/addons page:

This pull request worked for me, rtrim's another way of doing it too:
```
$directory = Str::remove(rtrim($autoload, '/'), dirname($reflector->getFileName()));
```

**Comment by bengs** [comment]
I had this problem too (on Mac OS) with a default demo install you'll get FileNotFoundException exception for the stripe add-on when visiting the `/hub/settings/addons` page:
File does not exist at path `/Users/username/Sites/getcandydemo/vendor/getcandy/stripe/srccomposer.json`. 

You can replicate the error on an existing install by deleting the addons manifest cache if it exists at:
`/bootstrap/cache/getcandy_addons.php` then visiting the /hub/settings/addons page:

This pull request worked for me, rtrim's another way of doing it too:
```
$directory = Str::remove(rtrim($autoload, '/'), dirname($reflector->getFileName()));
```

**Comment by alecritson** [comment]
Sorry for the delay on this one. I've had a look at it a bit and although it works, I quite like @bengs suggestion of `rtrim` since we only want to remove the last `/` from the string, I'm thinking `str_replace` all `/` is a little destructive. What do you think @glennjacobs ?

**Pull request merged**
