### PR TITLE
update/admin/collection-group

### PR DESCRIPTION
**Pull request by markmead**
This PR has the following.

**Added** - Group name when moving collection
**Fixed** - Side menu not stacking

Screenshot 2022-07-27 at 13 55 00

### CODE REVIEW

**Review by glennjacobs — APPROVED** [review]

**Comment by wychoong** [comment]
hey, thanks! was going to start looking into this myself
while you at it do you think it will be good to add the same in product page
image

**Comment by markmead** [comment]
Sounds like a plan @wychoong do you wanna create a new PR for that? Looks like you've already got it working 🎉

**Comment by wychoong** [comment]
If you don’t mind I push it here?

**Comment by markmead** [comment]
I'd say make a new PR from this one and request to merge your changes into it.

**Comment by wychoong** [comment]
#431

**Comment by markmead** [comment]
Here's the latest with @wychoong changes!

**Collections - Moving**

Screenshot 2022-07-29 at 11 49 05

**Product Collections**

Screenshot 2022-07-29 at 11 47 34

---

There were some issues with flex wrapping so I've added `flex-wrap` as a solution. Here's the before without `flex-wrap` 😅 

Screenshot 2022-07-29 at 11 48 15

Screenshot 2022-07-29 at 11 48 01

**Comment by alecritson** [comment]
@markmead If you go to a product and attach a collection, when searching the results come back like so:

image

I assume since we've changed breadcrumbs to an array this needs updating. I think it's this file [`packages/admin/resources/views/livewire/components/collection-search.blade.php`](https://github.com/getcandy/getcandy/blob/main/packages/admin/resources/views/livewire/components/collection-search.blade.php#L62)

**Review by glennjacobs — APPROVED** [review]

**Pull request merged**
