### PR TITLE
feat[Core]: Add base_price accessor to Product model

### PR DESCRIPTION
**Pull request by poppabear8883**
Usage example: `$product->base_price->formatted`

```blade
<product-card name="{{$product->translateAttribute('name')}}"
                        price="{{$product->base_price->formatted}}"
                        image=""
></product-card>
```

The way it currently is used in the hub looks something like this and this PR can make this approach cleaner:
```blade
@php
    $price = $variant->basePrices->first(fn($price) => $price->currency->default);
@endphp
{{ $price->price->formatted }}
```

### CODE REVIEW

**Comment by glennjacobs** [comment]
OK, so you're looking for a convenient way to get the base price for a product (not a variant). I don't think this is the correct approach. I will discuss with @alecritson tomorrow and make suggestions.

**Comment by poppabear8883** [comment]
I was under the impression that a `product` with `no variants` still uses a `variant` under the hood for the price so I was assuming that the variants collection would return the base variant and that's what would own the base price. Now that I have `tinkered` with it I can see that the "under the hood variant" is not included in the products variants collection.

I'm trying to reverse engineer the *hub* to see what approaches your team has taken.

I am also noticing that when i initially create a product with variants it does ask for a `Base Price` ... then I save the product and then I can edit the variant pricing, but the base price is no longer there ? Is this by design ?

**Comment by glennjacobs** [comment]
> I am also noticing that when i initially create a product with variants it does ask for a `Base Price` ... then I save the product and then I can edit the variant pricing, but the base price is no longer there ? Is this by design ?

Sounds odd. I'll review with Alec in the morning. But regardless, I'm not keen on pricing functionality on something that isn't purchasable. We also have the Pricing Manager coming in beta8 which will no doubt likely cover your requirements and more.

**Comment by poppabear8883** [comment]
> But regardless, I'm not keen on pricing functionality on something that isn't purchasable.

Its not really "pricing functionality". Its just an Accessor ... to help display data in a more elegant way.

> We also have the Pricing Manager coming in beta8 which will no doubt likely cover your requirements and more.

Awesome, I'm ok with just closing this PR if you find that there is no need for it.

**Comment by glennjacobs** [comment]
Closing as I believe the new Pricing Manager functionality will make this requirement redundant.

**Pull request closed without merging**
